### ISSUE TITLE
License of inject-x86_64.c

### ISSUE THREAD

**Issue by kubo** [unknownv2/CoreHook.ProcessInjection#3]
[`inject-x86_64.c` in this repository](https://github.com/unknownv2/CoreHook.ProcessInjection/blob/master/Linux/inject-x86_64.c) was obviously derived from [`inject-x86_64.c` in linux-inject](https://github.com/gaffe23/linux-inject/blob/master/inject-x86_64.c). The linux-inject is [licensed under GPLv2](https://github.com/gaffe23/linux-inject/blob/master/LICENSE.txt). So the derived work must be under same license. Why CoreHook.ProcessInjection is under the MIT license? Did you get permission  from @gaffe23 to change the license of `inject-x86_64.c` to MIT?

**Comment by unknownv2** [comment]
No, thank you, I will change the LICENSE file now, but I am actually planning on using your library here https://github.com/kubo/injector since it works much better I've found.

**Comment by unknownv2** [comment]
Linux-inject code has all been removed from the repository, but if you read this, I just wanted to just say thank you for injector library, it's great work and a major improvement!

**Comment by kubo** [comment]
Thanks for using my injector. I made it just to prove my idea. I have two enhancement ideas about injector. However I'm now focusing other projects.

I closed this issue because GPLv2 files were removed.
